const LEVELS = [
  {
    id: 1,
    title: "THE BASICS",
    subtitle: "Learn the ropes",
    dialogue: [
      { speaker: 'nurse', text: "Good morning! A hospital liaison just sent us a new referral." },
      { speaker: 'nurse', text: "Let's see who we've got..." },
      { speaker: 'patient', patientIndex: 0, text: "Hello! I'm Sarah Chen. I'm 72 years old. Just here for routine recovery - nothing too serious!" },
      { speaker: 'nurse', text: "Welcome, Sarah! Let's find you the perfect room." },
      { speaker: 'nurse', text: "Here's our current room roster.", action: 'showRoster' },
      { speaker: 'nurse', text: "Drag Sarah's card into the best bed for her. Remember: no mixing genders in semi-private rooms!", action: 'enableDrag' },
    ],
    beds: [
      { id: '409-1', room: '409', type: 'semi-private', patient: { id: 'mary', name: 'Mary Johnson', gender: 'F', condition: null, isolation: false } },
      { id: '409-2', room: '409', type: 'semi-private', patient: null },
      { id: '410-1', room: '410', type: 'semi-private', patient: { id: 'john', name: 'John Davis', gender: 'M', condition: null, isolation: false } },
      { id: '410-2', room: '410', type: 'semi-private', patient: null },
      { id: '411', room: '411', type: 'private', patient: null },
    ],
    newPatients: [
      { id: 'sarah', name: 'Sarah Chen', age: 72, gender: 'F', condition: 'Stable', isolation: false },
    ],
    solution: {
      '409-1': 'mary',
      '409-2': 'sarah',
      '410-1': 'john',
      '410-2': null,
      '411': null,
    },
    completionText: "Perfect! Sarah is all settled in Room 409 with Mary. Both female patients sharing a semi-private room - exactly right!",
  },
  {
    id: 2,
    title: "THE ACCOMMODATION",
    subtitle: "Sometimes you gotta shuffle",
    dialogue: [
      { speaker: 'nurse', text: "Another referral just came in... and this one's a bit trickier." },
      { speaker: 'patient', patientIndex: 0, text: "Hi... I'm Linda Torres, 64 years old. I've been diagnosed with Influenza A... *cough*" },
      { speaker: 'nurse', text: "Influenza A! That means Linda needs ISOLATION in a private room. No roommates." },
      { speaker: 'nurse', text: "Let's check our room roster...", action: 'showRoster' },
      { speaker: 'nurse', text: "Hmm, the private room 411 is occupied by James. We might need to MOVE him first!" },
      { speaker: 'nurse', text: "You can drag existing patients to new beds too. Think about where James can go!", action: 'enableDrag' },
    ],
    beds: [
      { id: '409-1', room: '409', type: 'semi-private', patient: { id: 'mary', name: 'Mary Wu', gender: 'F', condition: null, isolation: false } },
      { id: '409-2', room: '409', type: 'semi-private', patient: null },
      { id: '410-1', room: '410', type: 'semi-private', patient: { id: 'robert', name: 'Robert Harris', gender: 'M', condition: null, isolation: false } },
      { id: '410-2', room: '410', type: 'semi-private', patient: null },
      { id: '411', room: '411', type: 'private', patient: { id: 'james', name: 'James Miller', gender: 'M', condition: null, isolation: false } },
    ],
    newPatients: [
      { id: 'linda', name: 'Linda Torres', age: 64, gender: 'F', condition: 'Influenza A', isolation: true },
    ],
    solution: {
      '409-1': 'mary',
      '409-2': null,
      '410-1': 'robert',
      '410-2': 'james',
      '411': 'linda',
    },
    completionText: "Excellent! You moved James to Room 410 with Robert - both males in a semi-private. And Linda gets the private room she needs for isolation. Smart thinking!",
  },
  {
    id: 3,
    title: "DOUBLE TROUBLE",
    subtitle: "Two at once!",
    dialogue: [
      { speaker: 'nurse', text: "Whoa - busy day! We just got TWO referrals at the same time!" },
      { speaker: 'patient', patientIndex: 0, text: "Hi there! I'm Maria Santos, 58 years old. Just need a regular room - I'm feeling fine!" },
      { speaker: 'patient', patientIndex: 1, text: "*cough cough* ... I'm Tom Bradley... 75 years old... Influenza B... *wheeze*" },
      { speaker: 'nurse', text: "OK! Maria needs a regular bed, and Tom needs ISOLATION in a private room." },
      { speaker: 'nurse', text: "Let's see what we're working with...", action: 'showRoster' },
      { speaker: 'nurse', text: "Two patients, limited beds. You might need to shuffle someone around. You've got this!", action: 'enableDrag' },
    ],
    beds: [
      { id: '409-1', room: '409', type: 'semi-private', patient: { id: 'helen', name: 'Helen Park', gender: 'F', condition: null, isolation: false } },
      { id: '409-2', room: '409', type: 'semi-private', patient: null },
      { id: '410-1', room: '410', type: 'semi-private', patient: { id: 'george', name: 'George Lee', gender: 'M', condition: null, isolation: false } },
      { id: '410-2', room: '410', type: 'semi-private', patient: null },
      { id: '411', room: '411', type: 'private', patient: { id: 'james2', name: 'James Wilson', gender: 'M', condition: null, isolation: false } },
    ],
    newPatients: [
      { id: 'maria', name: 'Maria Santos', age: 58, gender: 'F', condition: 'Stable', isolation: false },
      { id: 'tom', name: 'Tom Bradley', age: 75, gender: 'M', condition: 'Influenza B', isolation: true },
    ],
    solution: {
      '409-1': 'helen',
      '409-2': 'maria',
      '410-1': 'george',
      '410-2': 'james2',
      '411': 'tom',
    },
    completionText: "Amazing work! Maria joins Helen in 409, James moved in with George in 410, and Tom gets the private room for isolation. You handled a double admission like a pro!",
  },
  {
    id: 4,
    title: "THE SWAP",
    subtitle: "Think ahead",
    dialogue: [
      { speaker: 'nurse', text: "We've got a tricky situation on our hands..." },
      { speaker: 'patient', patientIndex: 0, text: "*cough* Hey... I'm Derek Owens, 68 years old. Influenza A... I'm not feeling great." },
      { speaker: 'nurse', text: "Influenza A means Derek needs ISOLATION - a private room, no exceptions." },
      { speaker: 'nurse', text: "But look at this roster... the private room is already taken!", action: 'showRoster' },
      { speaker: 'nurse', text: "You'll need to shuffle someone out of that private room first. Think about who can safely share!", action: 'enableDrag' },
    ],
    beds: [
      { id: '501-1', room: '501', type: 'semi-private', patient: { id: 'ruth', name: 'Ruth Adams', gender: 'F', condition: 'Influenza - recovering', isolation: false } },
      { id: '501-2', room: '501', type: 'semi-private', patient: null },
      { id: '502-1', room: '502', type: 'semi-private', patient: { id: 'frank', name: 'Frank Lopez', gender: 'M', condition: null, isolation: false } },
      { id: '502-2', room: '502', type: 'semi-private', patient: null },
      { id: '503', room: '503', type: 'private', patient: { id: 'carol', name: 'Carol Bennett', gender: 'F', condition: 'Influenza - recovering', isolation: false } },
    ],
    newPatients: [
      { id: 'derek', name: 'Derek Owens', age: 68, gender: 'M', condition: 'Influenza A', isolation: true },
    ],
    solution: {
      '501-1': 'ruth',
      '501-2': 'carol',
      '502-1': 'frank',
      '502-2': null,
      '503': 'derek',
    },
    completionText: "Brilliant! You moved Carol in with Ruth - both females recovering together. And Derek gets the private room he needs for isolation. Strategic thinking!",
  },
];
